import type { ReportingModuleDefinition } from './types';

export const modalities = [
  'X-ray',
  'Ultrasound',
  'CT',
  'MRI',
  'Mammography',
  'Nuclear Medicine',
  'Interventional Radiology',
] as const;

export const bodySystems = [
  'Neuro',
  'Chest',
  'Abdomen/Pelvis',
  'MSK',
  'Vascular',
  'GU',
  'Breast',
  'Pediatrics',
  'Oncology',
] as const;

export const reportingModules: ReportingModuleDefinition[] = [
  {
    id: 'xray-cxr-pneumonia',
    title: 'Chest X-ray: pneumonia / infection',
    modality: 'X-ray',
    bodySystem: 'Chest',
    status: 'placeholder',
    description: 'Structured airspace opacity, distribution, complications, and follow-up language.',
    checklistPreview: ['Airspace opacity pattern', 'Pleural effusion', 'Cavitation', 'Follow-up recommendation'],
  },
  {
    id: 'xray-cxr-chf',
    title: 'Chest X-ray: CHF / pulmonary edema',
    modality: 'X-ray',
    bodySystem: 'Chest',
    status: 'placeholder',
    description: 'Pulmonary vascular congestion, edema pattern, effusions, and cardiac size.',
    checklistPreview: ['Cardiomediastinal size', 'Interstitial/alveolar edema', 'Pleural effusions', 'Comparison'],
  },
  {
    id: 'xray-cxr-pneumothorax',
    title: 'Chest X-ray: pneumothorax',
    modality: 'X-ray',
    bodySystem: 'Chest',
    status: 'placeholder',
    description: 'Pneumothorax presence, size estimate, tension features, and tube status.',
    checklistPreview: ['Side and size', 'Tension features', 'Chest tube position', 'Serial comparison'],
  },
  {
    id: 'xray-cxr-effusion',
    title: 'Chest X-ray: pleural effusion',
    modality: 'X-ray',
    bodySystem: 'Chest',
    status: 'placeholder',
    description: 'Effusion laterality, size, loculation clues, and associated pulmonary findings.',
    checklistPreview: ['Laterality', 'Size', 'Associated opacity', 'Loculation concern'],
  },
  {
    id: 'xray-cxr-lines',
    title: 'Chest X-ray: line/tube placement',
    modality: 'X-ray',
    bodySystem: 'Chest',
    status: 'placeholder',
    description: 'Support device position, complications, and actionable placement language.',
    checklistPreview: ['ET tube', 'Enteric tube', 'Central line', 'Pneumothorax check'],
  },
  {
    id: 'xray-abd-obstruction',
    title: 'Abdomen X-ray: bowel obstruction / ileus',
    modality: 'X-ray',
    bodySystem: 'Abdomen/Pelvis',
    status: 'placeholder',
    description: 'Bowel gas pattern, dilation, air-fluid levels, and free air screening.',
    checklistPreview: ['Small/large bowel dilation', 'Air-fluid levels', 'Rectal gas', 'Free air'],
  },
  {
    id: 'xray-abd-constipation',
    title: 'Abdomen X-ray: constipation / fecal loading',
    modality: 'X-ray',
    bodySystem: 'Abdomen/Pelvis',
    status: 'placeholder',
    description: 'Stool burden language with obstruction and complication checks.',
    checklistPreview: ['Stool burden', 'Bowel caliber', 'Rectal stool ball', 'Obstruction signs'],
  },
  {
    id: 'xray-msk-trauma',
    title: 'MSK X-ray: trauma/fracture',
    modality: 'X-ray',
    bodySystem: 'MSK',
    status: 'placeholder',
    description: 'Fracture, alignment, soft tissue swelling, and hardware-aware reporting.',
    checklistPreview: ['Fracture location', 'Displacement', 'Joint alignment', 'Soft tissues'],
  },
  {
    id: 'xray-msk-arthritis',
    title: 'MSK X-ray: arthritis / degenerative disease',
    modality: 'X-ray',
    bodySystem: 'MSK',
    status: 'placeholder',
    description: 'Joint space, osteophytes, erosions, and inflammatory arthropathy clues.',
    checklistPreview: ['Joint space narrowing', 'Osteophytes', 'Erosions', 'Alignment'],
  },
  {
    id: 'xray-spine-trauma',
    title: 'Spine X-ray: trauma/alignment',
    modality: 'X-ray',
    bodySystem: 'MSK',
    status: 'placeholder',
    description: 'Alignment, vertebral height, degenerative change, and acute osseous concern.',
    checklistPreview: ['Alignment', 'Vertebral body height', 'Prevertebral soft tissues', 'Degeneration'],
  },
  {
    id: 'us-ruq-biliary',
    title: 'RUQ ultrasound: cholelithiasis/cholecystitis/biliary obstruction',
    modality: 'Ultrasound',
    bodySystem: 'Abdomen/Pelvis',
    status: 'implemented',
    implementedModuleType: 'ruqUltrasound',
    description: 'Gallstones, wall thickening, Murphy sign, ductal dilation, and liver/biliary context.',
    checklistPreview: ['Gallstones/sludge', 'Wall/pericholecystic fluid', 'CBD caliber', 'Sonographic Murphy sign'],
  },
  {
    id: 'us-renal-bladder',
    title: 'Renal/bladder ultrasound: hydronephrosis/stone/retention',
    modality: 'Ultrasound',
    bodySystem: 'GU',
    status: 'placeholder',
    description: 'Hydronephrosis, stones, renal size, bladder volume, and post-void residual.',
    checklistPreview: ['Hydronephrosis grade', 'Stone/shadowing', 'Renal cortical appearance', 'PVR'],
  },
  {
    id: 'us-pelvic-pain',
    title: 'Pelvic ultrasound: pelvic pain/adnexal lesion',
    modality: 'Ultrasound',
    bodySystem: 'GU',
    status: 'placeholder',
    description: 'Ovarian/adnexal findings, torsion clues, free fluid, and uterine context.',
    checklistPreview: ['Ovarian size/flow', 'Adnexal mass', 'Free fluid', 'Uterus/endometrium'],
  },
  {
    id: 'us-pelvic-aub',
    title: 'Pelvic ultrasound: abnormal uterine bleeding',
    modality: 'Ultrasound',
    bodySystem: 'GU',
    status: 'placeholder',
    description: 'Endometrial thickness, fibroids, polyps, and cycle/menopausal context.',
    checklistPreview: ['Endometrial thickness', 'Fibroids', 'Focal lesion', 'Ovaries'],
  },
  {
    id: 'us-early-pregnancy',
    title: 'Early pregnancy ultrasound: viability/ectopic concern',
    modality: 'Ultrasound',
    bodySystem: 'GU',
    status: 'placeholder',
    description: 'Pregnancy location, viability markers, adnexa, and free fluid.',
    checklistPreview: ['IUP location', 'CRL/FHR', 'Adnexa', 'Free fluid'],
  },
  {
    id: 'us-thyroid-tirads',
    title: 'Thyroid ultrasound: TI-RADS',
    modality: 'Ultrasound',
    bodySystem: 'Neuro',
    status: 'placeholder',
    description: 'Nodule morphology, TI-RADS scoring support, and follow-up/FNA phrasing.',
    checklistPreview: ['Composition', 'Echogenicity', 'Margins', 'Echogenic foci'],
  },
  {
    id: 'us-scrotal',
    title: 'Scrotal ultrasound: torsion/epididymitis/mass',
    modality: 'Ultrasound',
    bodySystem: 'GU',
    status: 'placeholder',
    description: 'Testicular perfusion, epididymal findings, hydrocele/varicocele, and mass description.',
    checklistPreview: ['Testicular flow', 'Epididymis', 'Mass', 'Hydrocele/varicocele'],
  },
  {
    id: 'us-dvt',
    title: 'Lower-limb venous ultrasound: DVT',
    modality: 'Ultrasound',
    bodySystem: 'Vascular',
    status: 'implemented',
    implementedModuleType: 'dvtUltrasound',
    description: 'Compressibility, thrombus extent, acuity language, and calf vein limitations.',
    checklistPreview: ['Compressibility', 'Thrombus extent', 'Acute/chronic features', 'Calf veins'],
  },
  {
    id: 'ct-head-trauma',
    title: 'CT head: trauma',
    modality: 'CT',
    bodySystem: 'Neuro',
    status: 'placeholder',
    description: 'Hemorrhage, fracture, mass effect, and extra-axial collection checklist.',
    checklistPreview: ['Hemorrhage', 'Skull fracture', 'Mass effect', 'Extra-axial collection'],
  },
  {
    id: 'ct-head-stroke-aspects',
    title: 'CT head: stroke/ASPECTS',
    modality: 'CT',
    bodySystem: 'Neuro',
    status: 'implemented',
    implementedModuleType: 'stroke',
    description: 'Non-contrast CT stroke reporting with ASPECTS checklist and impression language.',
    checklistPreview: ['Hemorrhage', 'Early ischemic change', 'ASPECTS regions', 'Mass effect'],
  },
  {
    id: 'ct-head-headache',
    title: 'CT head: headache/acute intracranial abnormality',
    modality: 'CT',
    bodySystem: 'Neuro',
    status: 'placeholder',
    description: 'Hemorrhage, mass effect, hydrocephalus, and major structural abnormality language.',
    checklistPreview: ['Hemorrhage', 'Mass effect', 'Hydrocephalus', 'Comparison'],
  },
  {
    id: 'ct-cspine-trauma',
    title: 'CT C-spine: trauma',
    modality: 'CT',
    bodySystem: 'MSK',
    status: 'placeholder',
    description: 'Alignment, fracture, prevertebral soft tissues, and degenerative narrowing.',
    checklistPreview: ['Alignment', 'Fracture', 'Prevertebral soft tissues', 'Canal stenosis'],
  },
  {
    id: 'ctpa-pe',
    title: 'CTPA: pulmonary embolism',
    modality: 'CT',
    bodySystem: 'Chest',
    status: 'implemented',
    implementedModuleType: 'ctpa',
    description: 'PE presence, embolus level, RV/LV ratio, infarct, effusion, and alternative findings.',
    checklistPreview: ['PE level/laterality', 'RV/LV ratio', 'Infarct', 'Alternative diagnosis'],
  },
  {
    id: 'ct-chest-nodule',
    title: 'CT chest: pulmonary nodule/Fleischner',
    modality: 'CT',
    bodySystem: 'Chest',
    status: 'implemented',
    implementedModuleType: 'nodule',
    description: 'Nodule descriptor and simplified Fleischner follow-up language with applicability warnings.',
    checklistPreview: ['Nodule type', 'Size/location', 'Risk/applicability', 'Follow-up language'],
  },
  {
    id: 'ct-chest-pneumonia-ild-mass',
    title: 'CT chest: pneumonia/ILD/mass',
    modality: 'CT',
    bodySystem: 'Chest',
    status: 'placeholder',
    description: 'Parenchymal abnormality pattern, distribution, chronicity, and malignancy concern.',
    checklistPreview: ['Pattern', 'Distribution', 'Airway/pleura', 'Mass or adenopathy'],
  },
  {
    id: 'ct-ap-abdominal-pain',
    title: 'CT abdomen/pelvis: abdominal pain general',
    modality: 'CT',
    bodySystem: 'Abdomen/Pelvis',
    status: 'placeholder',
    description: 'Structured acute abdomen search pattern and alternative diagnosis language.',
    checklistPreview: ['Bowel', 'Solid organs', 'Free fluid/air', 'Urinary tract'],
  },
  {
    id: 'ct-ap-appendicitis',
    title: 'CT abdomen/pelvis: appendicitis',
    modality: 'CT',
    bodySystem: 'Abdomen/Pelvis',
    status: 'implemented',
    implementedModuleType: 'appendicitis',
    description: 'Appendix visualization, diameter, inflammatory change, and complications.',
    checklistPreview: ['Appendix diameter', 'Inflammation', 'Appendicolith', 'Abscess/perforation'],
  },
  {
    id: 'ct-ap-diverticulitis',
    title: 'CT abdomen/pelvis: diverticulitis',
    modality: 'CT',
    bodySystem: 'Abdomen/Pelvis',
    status: 'placeholder',
    description: 'Diverticulitis severity, abscess, perforation, obstruction, and follow-up flags.',
    checklistPreview: ['Segment involved', 'Abscess', 'Free air', 'Complication'],
  },
  {
    id: 'ct-ap-bowel-obstruction',
    title: 'CT abdomen/pelvis: bowel obstruction',
    modality: 'CT',
    bodySystem: 'Abdomen/Pelvis',
    status: 'implemented',
    implementedModuleType: 'bowelObstruction',
    description: 'Transition point, obstruction grade, ischemia clues, and cause.',
    checklistPreview: ['Transition point', 'Closed-loop signs', 'Ischemia', 'Cause'],
  },
  {
    id: 'ct-kub-renal-colic',
    title: 'CT KUB/renal colic',
    modality: 'CT',
    bodySystem: 'GU',
    status: 'implemented',
    implementedModuleType: 'renalColic',
    description: 'Stone location/size, hydronephrosis, alternative diagnoses, and renal findings.',
    checklistPreview: ['Stone size/location', 'Hydronephrosis', 'Perinephric stranding', 'Alternative finding'],
  },
  {
    id: 'ct-trauma-cap',
    title: 'CT trauma chest/abdomen/pelvis',
    modality: 'CT',
    bodySystem: 'Abdomen/Pelvis',
    status: 'placeholder',
    description: 'Trauma checklist across chest, solid organs, bowel/mesentery, pelvis, and spine.',
    checklistPreview: ['Thoracic injury', 'Solid organ injury', 'Free fluid/air', 'Pelvic/spine injury'],
  },
  {
    id: 'ct-aorta',
    title: 'CT aorta: dissection/aneurysm',
    modality: 'CT',
    bodySystem: 'Vascular',
    status: 'placeholder',
    description: 'Aortic caliber, dissection flap, branch involvement, rupture signs, and follow-up.',
    checklistPreview: ['Aortic segments', 'Dissection flap', 'Branch vessels', 'Rupture signs'],
  },
  {
    id: 'ct-adrenal-washout',
    title: 'CT adrenal lesion: washout',
    modality: 'CT',
    bodySystem: 'Abdomen/Pelvis',
    status: 'placeholder',
    description: 'Adrenal lesion attenuation, washout values, and adenoma-supportive wording.',
    checklistPreview: ['Noncontrast HU', 'Enhanced HU', 'Delayed HU', 'Washout thresholds'],
  },
  {
    id: 'ct-renal-bosniak',
    title: 'CT renal mass/cyst: Bosniak',
    modality: 'CT',
    bodySystem: 'GU',
    status: 'placeholder',
    description: 'Cystic renal lesion features and simplified Bosniak classification support.',
    checklistPreview: ['Septa', 'Wall thickness', 'Enhancement', 'Nodular component'],
  },
  {
    id: 'mri-brain-stroke',
    title: 'MRI brain: stroke',
    modality: 'MRI',
    bodySystem: 'Neuro',
    status: 'placeholder',
    description: 'DWI/ADC, hemorrhage-sensitive sequence, vascular territory, and chronic ischemic burden.',
    checklistPreview: ['DWI/ADC', 'Hemorrhage', 'Territory', 'Chronic findings'],
  },
  {
    id: 'mri-brain-mass',
    title: 'MRI brain: mass',
    modality: 'MRI',
    bodySystem: 'Neuro',
    status: 'placeholder',
    description: 'Mass location, enhancement, edema, mass effect, and differential-ready descriptors.',
    checklistPreview: ['Location', 'Enhancement', 'Edema', 'Mass effect'],
  },
  {
    id: 'mri-brain-ms',
    title: 'MRI brain: demyelination/MS',
    modality: 'MRI',
    bodySystem: 'Neuro',
    status: 'placeholder',
    description: 'Demyelinating lesion distribution, enhancement, comparison, and dissemination support.',
    checklistPreview: ['Periventricular', 'Juxtacortical', 'Infratentorial', 'Enhancement'],
  },
  {
    id: 'mri-brain-seizure',
    title: 'MRI brain: seizure',
    modality: 'MRI',
    bodySystem: 'Neuro',
    status: 'placeholder',
    description: 'Mesial temporal sclerosis, malformation, mass, injury, and cortical signal change.',
    checklistPreview: ['Hippocampi', 'Cortical malformation', 'Mass', 'Gliosis'],
  },
  {
    id: 'mri-spine-cauda',
    title: 'MRI spine: cauda equina',
    modality: 'MRI',
    bodySystem: 'Neuro',
    status: 'placeholder',
    description: 'Canal stenosis, compression, disc extrusion, and urgent communication language.',
    checklistPreview: ['Level', 'Canal compromise', 'Nerve root compression', 'Urgent findings'],
  },
  {
    id: 'mri-spine-infection-malignancy',
    title: 'MRI spine: infection/malignancy',
    modality: 'MRI',
    bodySystem: 'Neuro',
    status: 'placeholder',
    description: 'Discitis/osteomyelitis, epidural disease, marrow replacement, and abscess.',
    checklistPreview: ['Marrow signal', 'Disc/endplates', 'Epidural component', 'Paraspinal soft tissues'],
  },
  {
    id: 'mri-lumbar-radiculopathy',
    title: 'MRI lumbar spine: radiculopathy/degenerative disease',
    modality: 'MRI',
    bodySystem: 'MSK',
    status: 'placeholder',
    description: 'Level-by-level stenosis, disc disease, nerve root contact, and alignment.',
    checklistPreview: ['Disc bulge/protrusion', 'Canal stenosis', 'Foraminal stenosis', 'Nerve contact'],
  },
  {
    id: 'mri-prostate-pirads',
    title: 'MRI prostate: PI-RADS',
    modality: 'MRI',
    bodySystem: 'GU',
    status: 'placeholder',
    description: 'Lesion location, sequence scores, extraprostatic extension, and PI-RADS wording.',
    checklistPreview: ['Zone/location', 'DWI/T2/DCE', 'Capsule', 'Nodes/bone'],
  },
  {
    id: 'mri-liver-lirads',
    title: 'MRI liver: LI-RADS',
    modality: 'MRI',
    bodySystem: 'Abdomen/Pelvis',
    status: 'placeholder',
    description: 'Observation features, enhancement pattern, washout/capsule, and LI-RADS support.',
    checklistPreview: ['Arterial enhancement', 'Washout', 'Capsule', 'Threshold growth'],
  },
  {
    id: 'mri-rectal-cancer',
    title: 'MRI rectal cancer staging',
    modality: 'MRI',
    bodySystem: 'Oncology',
    status: 'placeholder',
    description: 'Tumor height, T stage, mesorectal fascia, EMVI, nodes, and sphincter involvement.',
    checklistPreview: ['Tumor height', 'T stage', 'MRF', 'EMVI/nodes'],
  },
  {
    id: 'mri-knee',
    title: 'MRI knee: meniscus/ligament/internal derangement',
    modality: 'MRI',
    bodySystem: 'MSK',
    status: 'placeholder',
    description: 'Menisci, cruciate/collateral ligaments, cartilage, marrow, and effusion.',
    checklistPreview: ['Menisci', 'ACL/PCL', 'Collateral ligaments', 'Cartilage/bone'],
  },
  {
    id: 'mri-shoulder',
    title: 'MRI shoulder: rotator cuff/labrum',
    modality: 'MRI',
    bodySystem: 'MSK',
    status: 'placeholder',
    description: 'Rotator cuff tendons, muscle atrophy, labrum, biceps, and arthritis.',
    checklistPreview: ['Rotator cuff', 'Labrum', 'Biceps', 'Muscle atrophy'],
  },
  {
    id: 'breast-birads',
    title: 'BI-RADS',
    modality: 'Mammography',
    bodySystem: 'Breast',
    status: 'placeholder',
    description: 'Breast imaging assessment category and recommendation language support.',
    checklistPreview: ['Finding type', 'Location', 'Assessment category', 'Recommendation'],
  },
  {
    id: 'breast-us-mass',
    title: 'Breast mass ultrasound',
    modality: 'Ultrasound',
    bodySystem: 'Breast',
    status: 'placeholder',
    description: 'Mass morphology, orientation, margins, posterior features, and BI-RADS-ready phrasing.',
    checklistPreview: ['Shape/orientation', 'Margins', 'Echogenicity', 'Posterior features'],
  },
  {
    id: 'breast-screen-callback',
    title: 'Screening mammography callback',
    modality: 'Mammography',
    bodySystem: 'Breast',
    status: 'placeholder',
    description: 'Callback reason, views needed, and comparison-aware language.',
    checklistPreview: ['Asymmetry/mass/calcifications', 'Location', 'Comparison', 'Next views'],
  },
  {
    id: 'oncology-recist',
    title: 'RECIST 1.1 measurement tracker',
    modality: 'CT',
    bodySystem: 'Oncology',
    status: 'placeholder',
    description: 'Target lesion sums, percent change, and simplified RECIST category support.',
    checklistPreview: ['Target lesions', 'Baseline sum', 'Current sum', 'Response category'],
  },
  {
    id: 'oncology-response',
    title: 'Treatment response comparison',
    modality: 'CT',
    bodySystem: 'Oncology',
    status: 'placeholder',
    description: 'Comparison framework for tumor burden, new lesions, and non-target disease.',
    checklistPreview: ['Target disease', 'Non-target disease', 'New lesions', 'Overall impression'],
  },
];
