import type { ReportingWorkflowSchema, WorkflowValues } from '../data/reportingWorkflowSchemas';
import type { ReportSections } from '../radrep/types';
import { cleanLines, workflowValue } from './impressionGenerators';

const v = (values: WorkflowValues, key: string) => workflowValue(values, key);
const lim = (values: WorkflowValues) => [v(values, 'technicalLimitations'), v(values, 'limitationsUncertainty')].filter(Boolean).join('; ');
const base = (schema: ReportingWorkflowSchema, values: WorkflowValues, findings: string, impression: string, recommendations: string): ReportSections => ({
  indication: cleanLines([v(values, 'clinicalIndication') || schema.clinicalQuestion, v(values, 'clinicalContext') ? `Context: ${v(values, 'clinicalContext')}.` : undefined, v(values, 'transplantHistory') ? `Transplant/operative history: ${v(values, 'transplantHistory')}.` : undefined]),
  technique: cleanLines([v(values, 'modalityProtocol') || schema.techniqueDefault, v(values, 'examQuality') ? `Quality: ${v(values, 'examQuality')}.` : undefined, lim(values) ? `Limitations: ${lim(values)}.` : undefined]),
  findings: v(values, 'findingsOverride') || findings, impression: v(values, 'impressionOverride') || impression,
  incidentalFindings: v(values, 'incidentalFindings'), recommendations,
});
const flagged = (values: WorkflowValues, label: string, key: string, details = '') => ['present', 'indeterminate', 'not assessed'].includes(v(values, key)) ? `${label}: ${v(values, key)}${details && v(values, details) ? `; ${v(values, details)}` : ''}.` : undefined;

export function generateLiverTransplantUltrasoundReport(schema: ReportingWorkflowSchema, values: WorkflowValues): ReportSections {
  const vessels = `Hepatic artery ${v(values, 'hepaticArteryPatency') || 'not entered'}${v(values, 'hepaticArteryWaveform') ? `, ${v(values, 'hepaticArteryWaveform')}` : ''}${v(values, 'hepaticArteryRi') ? `, RI ${v(values, 'hepaticArteryRi')}` : ''}${v(values, 'hepaticArteryPsv') ? `, PSV ${v(values, 'hepaticArteryPsv')} cm/s` : ''}. Portal vein ${v(values, 'portalVeinPatency') || 'not entered'}${v(values, 'portalFlowDirection') ? ` with ${v(values, 'portalFlowDirection')} flow` : ''}${v(values, 'portalVeinVelocity') ? ` at ${v(values, 'portalVeinVelocity')} cm/s` : ''}. Hepatic veins ${v(values, 'hepaticVeinPatency') || 'not entered'}${v(values, 'hepaticVeinWaveform') ? `, ${v(values, 'hepaticVeinWaveform')}` : ''}; IVC ${v(values, 'ivcPatency') || 'not entered'}.`;
  const urgent = flagged(values, 'Urgent vascular finding', 'urgentFinding', 'urgentDetails');
  const findings = cleanLines([v(values, 'graftAppearance') ? `Graft: ${v(values, 'graftAppearance')}.` : undefined, vessels, flagged(values, 'Biliary dilation', 'biliaryDilation', 'biliaryDetails'), flagged(values, 'Perihepatic collection', 'collection', 'collectionDetails'), urgent, lim(values) ? `Limitations: ${lim(values)}.` : undefined]);
  return base(schema, values, findings, cleanLines([v(values, 'examQuality') === 'limited' ? 'Limited liver-transplant Doppler examination.' : undefined, urgent || vessels, flagged(values, 'Biliary dilation', 'biliaryDilation', 'biliaryDetails'), flagged(values, 'Collection', 'collection', 'collectionDetails')]), 'No institution-specific threshold, diagnosis, treatment, or management advice is calculated. Verify technique, comparison, and communication.');
}
export function generateKidneyTransplantUltrasoundReport(schema: ReportingWorkflowSchema, values: WorkflowValues): ReportSections {
  const size = [v(values, 'graftLengthCm'), v(values, 'graftApCm'), v(values, 'graftTrCm')].filter(Boolean).join(' × ');
  const vessels = `Transplant renal artery ${v(values, 'renalArteryPatency') || 'not entered'}${v(values, 'anastomoticPsv') ? `, anastomotic PSV ${v(values, 'anastomoticPsv')} cm/s` : ''}; renal vein ${v(values, 'renalVeinPatency') || 'not entered'}. Intrarenal RI upper/mid/lower ${[v(values, 'riUpper'), v(values, 'riMid'), v(values, 'riLower')].filter(Boolean).join('/') || 'not entered'}.`;
  const urgent = flagged(values, 'Urgent vascular finding', 'urgentFinding', 'urgentDetails');
  const findings = cleanLines([size ? `Graft measures ${size} cm.` : undefined, v(values, 'graftEchogenicity') ? `Echogenicity: ${v(values, 'graftEchogenicity')}.` : undefined, flagged(values, 'Collecting-system dilation', 'collectingSystemDilation', 'collectingSystemDetails'), flagged(values, 'Peritransplant collection', 'collection', 'collectionDetails'), vessels, flagged(values, 'Waveform abnormality', 'waveformAbnormality', 'waveformDetails'), v(values, 'bladderFindings') ? `Bladder: ${v(values, 'bladderFindings')}.` : undefined, urgent]);
  return base(schema, values, findings, cleanLines([v(values, 'examQuality') === 'limited' ? 'Limited renal-transplant Doppler examination.' : undefined, urgent || vessels, flagged(values, 'Collecting-system dilation', 'collectingSystemDilation', 'collectingSystemDetails'), flagged(values, 'Collection', 'collection', 'collectionDetails')]), 'No institution-specific threshold, stenosis diagnosis, treatment, or management advice is calculated. Verify technique, measurements, comparison, and communication.');
}
export function generateLivingDonorLiverReport(schema: ReportingWorkflowSchema, values: WorkflowValues): ReportSections {
  const volumes = `Volumes: total ${v(values, 'totalLiverVolumeMl') || 'not entered'} mL; ${v(values, 'proposedGraft') || 'proposed graft'} ${v(values, 'graftVolumeMl') || 'not entered'} mL; remnant ${v(values, 'remnantVolumeMl') || 'not entered'} mL.`;
  const anatomy = cleanLines([v(values, 'arterialAnatomy') ? `Arterial: ${v(values, 'arterialAnatomy')}; variants: ${v(values, 'arterialVariants') || 'none entered'}.` : undefined, v(values, 'portalAnatomy') ? `Portal: ${v(values, 'portalAnatomy')}; variants: ${v(values, 'portalVariants') || 'none entered'}.` : undefined, v(values, 'hepaticVenousAnatomy') ? `Hepatic venous: ${v(values, 'hepaticVenousAnatomy')}; variants: ${v(values, 'venousVariants') || 'none entered'}.` : undefined, v(values, 'biliaryAnatomy') ? `Biliary: ${v(values, 'biliaryAnatomy')}; variants: ${v(values, 'biliaryVariants') || 'none entered'}.` : undefined]);
  const findings = cleanLines([v(values, 'liverMorphology') ? `Liver: ${v(values, 'liverMorphology')}.` : undefined, flagged(values, 'Focal lesion', 'liverLesion', 'liverLesionDetails'), flagged(values, 'Steatosis', 'steatosis', 'steatosisDetails'), volumes, v(values, 'userVolumeRatios') ? `User-entered ratios: ${v(values, 'userVolumeRatios')}.` : undefined, anatomy, v(values, 'surgicalPlanes') ? `Surgical planes: ${v(values, 'surgicalPlanes')}.` : undefined, v(values, 'venousDrainage') ? `Venous drainage: ${v(values, 'venousDrainage')}.` : undefined]);
  return base(schema, values, findings, cleanLines([v(values, 'examQuality') === 'limited' ? 'Limited living-donor liver evaluation.' : undefined, v(values, 'userSuitabilitySynthesis') || 'Donor anatomy and volumetry mapped; program synthesis not entered.', anatomy]), 'No donor eligibility, graft suitability, volumetric threshold, surgery, treatment, or management advice is calculated. Verify program protocol and all anatomy.');
}
